### PR TITLE
Added user-agent support

### PR DESCRIPTION
**Pull request by tognee**
Added user-agent support for gtk, in reference to #498

### CODE REVIEW

**Comment by r0x0r** [comment]
I am not fond of passing user_agent to a window. 
A parameter to `webview.start(user_agent='')` similar to gui would me a more apt choice imo, even though it would make user agent global for the application.

**Comment by tognee** [comment]
I've looked into other renderers and it seems like not all have this option to change the user-agent.

For my usecase I need to open a window, get some data from a site that's only obtainable with a specific user-agent and then close the window and send the data to the frontend.
Using a global user-agent should work as well, but then the entire app uses that user-agent.

**Comment by r0x0r** [comment]
Personally I see no problem in having a global user-agent. At least I cannot think of any use-case where it would be beneficial to have a unique user-agent for each window. 
Another solution could be setting a user agent in a similar war as Chrome settings are passed to CEF, ie https://github.com/r0x0r/pywebview/blob/master/examples/cef.py

**Comment by tognee** [comment]
I've now removed the user_agent reference from the window __init__ and implemented the settings method already used by cef.
Did a test on gtk, qt, cocoa and cef and it works.

Now winforms is the only one missing. Need to make a VM to do MSHTML and then I will look into EdgeHTML

**Comment by tognee** [comment]
Ok, so I've tested MSHTML on a Win7 VM and it works as well.

Now only EdgeHTML is left. I'm not good with c# so I think I'll need help with that one

**Comment by r0x0r** [comment]
Good job. Would you mind adding an example too?
I would not stress about EdgeHTML, it can be marked as unsupported for now. Microsoft is promising Chromium based WebView2 sometime soon, so it looks like EdgeHTML will become obsolete in any case.

**Comment by r0x0r** [comment]
Let's user_agent parameter to the start function to make it more accessible. I will continue from that.
Thanks for the contribution!

**Pull request merged**
