### PR TITLE
Fix Change the placement of WebView2Loader.dll (issue #1078)

### LINKED ISSUE #1078: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found.
### Specification
- pywebview version:  4.0.2
- operating system: Windows 10 / Windows 11 (tested on both)
- web renderer: WebView2

### Description  
  
```
[pywebview] WebView2 initialization failed with exception:
 Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()  
```

To fix, I had to move WebView2Loader.dll from
.venv\Lib\site-packages\webview\lib\x64\WebView2Loader.dll
to
.venv\Lib\site-packages\webview\lib\WebView2Loader.dll

It seems the issue is solely based on the .dll being within the /x64 folder

### Practicalities

- YES - I am willing to work on this issue myself.

- NO - I am prepared to support this issue financially. (I have no personal or professional financial resources to support with, sorry).

### PR DESCRIPTION
**Pull request by kawana77b**
This PR fixes #1078 and allows Pywebview to run with Python installed via the Microsoft Store.

## Issue
For normal officially installed Python and Anaconda-like environments, WebView2 works fine as it searches the directory added to `Path` for the `WebView2Loader.dll`.
However, Python.exe installed from the Micorosoft Store do not search the `Path`.
These occur commonly in several MS Store versions of Python, such as Python 3.10 and Python 3.11.

## Fixes
As a simple solution, I have moved `WebView2Loader.dll` to the folder structure indicated by the following link.
Also, changed the name of the `interop_dll_path()` definition platform.
I have added a process to allow functions to discover directories, so that they can be added to `PATH` as before.
I ensured that WebView2Loader.dll is discovered to avoid errors,
I expect Pywebview to be available on many Windows Python platforms.

// reference: files to ship with the app
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

## How to check
Build venv with the MS Store version and Anaconda and check that python and pytest are available in each environment.
Since `pytest tests` cannot check for exceptions and the test stops, do the same test with `tests/run.ps1`.
The MS Store version had an exception similar to the issue, but this commit confirms that all tests pass.

## Notes
I have no experience with PRs, so please feel free to send me any additional details to test or fix. I will make every possible effort.
Due to lack of knowledge in some areas, you may reject the PR if you can determine that the solution to this problem is not something that should be merged.
Thanks for reading! And thank you for all your great initiatives!

### CODE REVIEW

**Comment by r0x0r** [comment]
Thanks for the thorough PR.
Would you change double to single quotes to match the rest of the project?

**Comment by kawana77b** [comment]
Thanks for pointing this out. The relevant sections have been amended.

**Comment by ZenithRogue** [comment]
@r0x0r Do you have a timeline for this patch being pushed through to pip?

**Comment by r0x0r** [comment]
@ZenithRogue I will make a new release this week

**Pull request merged**
