### PR TITLE
Solving: file access not allowed on "cef" renderer 

### PR DESCRIPTION
**Pull request by Mohamed501258**
using "cef" renderer will prevent the local files access, this edit will allow serving local files from different folders without problems.

### CODE REVIEW

**Comment by r0x0r** [comment]
Are there any other ramifications of disabling web security?

**Comment by Mohamed501258** [comment]
as we aim to create desktop applications that have full access to files on
the pc, I think it will not be problem

**Comment by r0x0r** [comment]
Disabling web security also disables CORS, SSL checks and OPTIONS. I don't think it would be a wise thing to disable it by default. Instead you could disable web security in your application like this.

```
from webview.platforms.cef import settings
settings.update({
    'disable_web_security': True
})
```

**Comment by Mohamed501258** [comment]
But this issue limits the access to files outside the working directory,
and of course when there is relatively big project it will be a problem.I
agree it is not safe, but is there any alternative solution for this? It is
supposed to be desktop application with full access to the files otherwise
it will affect the performance.
This is my opinion

بتاريخ الأحد، 1 أغسطس 2021، جاء من Roman ***@***.***>:

**Comment by r0x0r** [comment]
I agree that this is indeed an issue, but disabling web security is too of a drastic measure. I propose documenting the approach I had posted above.

**Comment by r0x0r** [comment]
CEF seems to have allow-file-access-from-files switch that is exactly what is needed

**Comment by Mohamed501258** [comment]
Yes, I agree. But the pros and cons of this modification should be
highlighted in the doc so who writes the code is aware of the security
issues

**Comment by Mohamed501258** [comment]
Yes it has, and I have tried this before but the file access doesn't work
unless I disable web security.


بتاريخ الثلاثاء، 3 أغسطس 2021، جاء من Roman ***@***.***>:

**Pull request closed without merging**
