### PR TITLE
Support python2.7: change getfullargspec() to getargspec()

### PR DESCRIPTION
**Pull request by zvibazak**
In order to support python2.7 change getfullargspec() to getargspec().

### CODE REVIEW

**Comment by r0x0r** [comment]
I am phasing out support for Python2. Is there a use case for keeping this Python2 compatible?

**Comment by zvibazak** [comment]
Yes we still use python 2   :)
I belive that there are another developers that the migration is too hard to them.

**Comment by r0x0r** [comment]
While I have no problems accepting this PR, I am not able to support Python2. Meaning that future changes might break Python2 compatibility once again. In a nutshell it is going to be somebody else’s responsibility to verify that pywebview works under Python 2.

**Comment by zvibazak** [comment]
Ok sounds great. I’ll push the fix I see.

**Comment by r0x0r** [comment]
getargspec has been deprecated since Python 3.0. Please introduce a condition to use getfullargspec if running under Python 3.

**Comment by zvibazak** [comment]
Done.

**Pull request merged**
