### PR TITLE
Add the feature that having an ability to daemonize the invoked func …

### PR DESCRIPTION
**Pull request by xiaofengsoft**
Add the feature that having an ability to daemonize the invoked func while starting the window

### CODE REVIEW

**Comment by r0x0r** [comment]
What's the use case for this? 
You can always start a callback manually in whatever way you want.

**Comment by xiaofengsoft** [comment]
Yeah, you re right, but this way may be more expedient. For example, when you need to close the called thread at the same time as closing the window.In this way, It just need you to pass a param.

**Comment by xiaofengsoft** [comment]
> What's the use case for this? 
> You can always start a callback manually in whatever way you want.

Yeah, you re right, but this way may be more expedient. For example, when you need to close the called thread at the same time as closing the window.In this way, It just need you to pass a param.

**Comment by r0x0r** [comment]
Thanks for the suggestion, but I am not going to accept this at this point.

**Pull request closed without merging**
