### PR TITLE
[WIP] Get size + position

### PR DESCRIPTION
**Pull request by Fizzadar**
WIP - wanted to get your thoughts before attempting to implement for QT/etc!

### CODE REVIEW

**Comment by r0x0r** [comment]
Cool, please go ahead.

I am not too keen on the names `get_position` and `get_size`, as with time it will be a bunch of `get_` methods. I cannot think of better names, though.
Maybe do it with properties?  E.g. `window.width`, `window.height`, `window.x`, and `window.y`. That would present a problem with setters, ie. should those be writeable as well. If so, then these properties would duplicate the functionality of `window.resize` and `window.move`. 
Thoughts are welcomed.

**Comment by Fizzadar** [comment]
@r0x0r agreed - the two get's are no good; I see two options:

+ `get_frame` (or similar) that returns both the x/y/width/height (as all require the same underlying call)
+ read-only window properties - each would need to make a different call to get the frame (in cocoa) which might not be efficient - but I do like the idea of a `window.width` and so on, it's a much nicer API for the end-user

What do you think? In the meantime will investigate implementing this for QT.

**Comment by r0x0r** [comment]
Let's go with read-only properties for now: x, y, width, height. If a need for a frame arises, it can be implemented later.

**Comment by Fizzadar** [comment]
bump. Hoping to get time to finish this up this week!

**Comment by Fizzadar** [comment]
@r0x0r have just pushed a re-implementation using properties - let me know what you think!

**Comment by r0x0r** [comment]
@Fizzadar looks good to me.
Would you be able to provide implementations for other platforms?

**Comment by Fizzadar** [comment]
@r0x0r yes I'm going to look into the other platforms over the holidays; only issue might be Winforms as I've no proper Windows testing environment.

**Comment by Fizzadar** [comment]
@r0x0r much delayed but have just pushed working implementations for QT+GTK (both tested on Mac).

**Comment by r0x0r** [comment]
There is an issue with properties, namely they must be wrapped with the `@_shown_call` decorator. Now calling any of the properties immediately after `webview.start()` results in an error.

**Comment by r0x0r** [comment]
There is a problem with retrieving window coordinates on Cocoa too.
If you set x=100, y=200 in `create_window` and retrieve them right after it will return x=100.0, y=100.0.

**Comment by r0x0r** [comment]
I have pushed my changes to the `Fizzadar-get-size-position` branch. Please update the PR with it.

There is a problem with retrieving correct window width on Cocoa as well, as demonstrated by `examples/resize.py`.

**Comment by r0x0r** [comment]
I have added Windows implementation, documentation and tests. The changes are in the `Fizzadar-get-size-position` branch.

**Comment by Fizzadar** [comment]
Thank you; have merged in your changes from the `Fizzadar-get-size-position` branch.

**Pull request merged**
