### PR TITLE
QtWebEngine: use OTR profile

### PR DESCRIPTION
**Pull request by obfusk**
Use an off-the-record QWebEngineProfile, instead of (unexpectedly) persisting cookies.

Related: #531

### CODE REVIEW

**Comment by r0x0r** [comment]
Could you add a parameter to `webview.start` as well, so user could choose whether to save cookies or not? In the ticket I specified a `clean` parameter, but on the second thoughts `incognito` would be better. The default signature should be `webview.start(incognito=True)`
It can be implemented in a similar manner as debug parameter.

**Comment by obfusk** [comment]
> Could you add a parameter to `webview.start` as well, so user could choose whether to save cookies or not? In the ticket I specified a `clean` parameter, but on the second thoughts `incognito` would be better. The default signature should be `webview.start(incognito=True)`
> It can be implemented in a similar manner as debug parameter.

Sure. The reason I didn't do that yet is that `qtwebkit` doesn't seem to have an easy way to have a *non*-incognito mode. So when `qtwebview` is not available I'd either have to error/warn/ignore when `incognito=False`. Or figure out a way to make it work.

How do you want to handle that?

**Comment by obfusk** [comment]
Also:

Where should it store the data by default? Currently `qtwebengine` uses a global shared profile (`~/.config/QtWebEngine/Default` on Linux iirc).

It seems only cookies are supported, not e.g. `localStorage` :(

I think it might be best to just make everything incognito for now. But maybe provide a hook at the appropriate place so a user can easily add their own logic.

**Comment by r0x0r** [comment]
logger.warning sounds like a plan for QtWebKit. Default location can be used as well.

Considering non-incognito mode is rather sketchy, it could be added as an experimental feature now and details can be ironed later on.

**Comment by obfusk** [comment]
I added the parameter and the warning.

**Pull request merged**
