### PR TITLE
Replace use of Thread with ThreadPoolExecutor

### PR DESCRIPTION
**Pull request by rotu**
Also log any error while evaluating callbacks, not just if thread creation fails.

### CODE REVIEW

**Comment by rotu** [comment]
Hmm... These [CI failures](https://ci.appveyor.com/project/r0x0r/pywebview/builds/27999402/job/big2ydevs3borljd) don't look like my fault:

```
Installing collected packages: attrs, colorama, more-itertools, zipp, importlib-metadata, pluggy, py, atomicwrites, six, pytest, pythonnet, cefpython3
Successfully installed atomicwrites-1.3.0 attrs-19.2.0 cefpython3-66.0 colorama-0.4.1 importlib-metadata-0.23 more-itertools-7.2.0 pluggy-0.13.0 py-1.8.0 pytest-4.2.0 pythonnet-2.4.0 six-1.12.0 zipp-0.6.0
You are using pip version 18.1, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
%CMD_IN_ENV% python -m pytest tests/test_bg_color.py -s
Traceback (most recent call last):
  File "C:\Python36-x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python36-x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-x64\lib\site-packages\pytest.py", line 89, in <module>
    raise SystemExit(pytest.main())
  File "C:\Python36-x64\lib\site-packages\_pytest\config\__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "C:\Python36-x64\lib\site-packages\_pytest\config\__init__.py", line 182, in _prepareconfig
    config = get_config()
  File "C:\Python36-x64\lib\site-packages\_pytest\config\__init__.py", line 156, in get_config
    pluginmanager.import_plugin(spec)
  File "C:\Python36-x64\lib\site-packages\_pytest\config\__init__.py", line 530, in import_plugin
    __import__(importspec)
  File "C:\Python36-x64\lib\site-packages\_pytest\tmpdir.py", line 25, in <module>
    class TempPathFactory(object):
  File "C:\Python36-x64\lib\site-packages\_pytest\tmpdir.py", line 35, in TempPathFactory
    lambda p: Path(os.path.abspath(six.text_type(p)))
TypeError: attrib() got an unexpected keyword argument 'convert'

```

**Comment by rotu** [comment]
ThreadPoolExecutor doesn't exist in Python2, so if legacy Python support is necessary, please close this PR unmerged.

**Comment by rotu** [comment]
did not intend to close this

**Comment by r0x0r** [comment]
Is this a fix to #390? I have tested with your example and it hangs randomly.

**Comment by rotu** [comment]
No, it’s not. This PR is intended to only reduce the maximum number of threads and to increase logging coverage when a python callback errors out.

**Comment by r0x0r** [comment]
Got it. This is a welcomed change.
As I mentioned in the previous comment this change hangs the app with a for loop.

```javascript
    for (let i = 0; i < 10; i++) {
        console.log('request ' + i);
        api.echo(i).then((j) => {
            console.log('response ' + i)
        })
    }
```
```python
class JSApi:
    def echo(self, value):
        print(value)
        return value
```

**Pull request closed without merging**
