### PR TITLE
WinForms with Edge WebView (WIP)

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
Hello,

This is an initial implementation of the Edge WebView backend for pywebview running under Windows 10 (April 2018 Update and later)

The basic functionalities are implemented. e.g. Loading from URL, invoking javascript, JS_api, ...

However some are still missing:
 - File download
 - load_html

Also some are buggy: e.g. Alert dialog

This implementation is also lacking lots of tests. I only tested some basic websites and static html files on my machine, that is running Windows 10 version 1809 with Python 3.

This is my first time dealing with C#, .NET and Windows development. So, I would appreciate some guidance solving the remaining issues...

Solves https://github.com/r0x0r/pywebview/issues/243

### CODE REVIEW

**Comment by r0x0r** [comment]
Thanks for the contribution. Much appreciated!
I will take a closer look late, but meanwhile a couple of words regarding the architecture. Considering this is WinForms based as well, it is better be done on top of  the existing `winforms.py` implementation with a healthy amount of conditions. I have done it this way in the CEF implementation [here](https://github.com/r0x0r/pywebview/blob/cef/webview/winforms.py). All the Edge initialisation could be done using inside a `_create_edge_browser` function. The best course of action would be probably to rebase your branch on top of the `cef` branch and go there. 
I will try to finish the CEF implementation soon to avoid conflicts.

**Comment by HeavenVolkoff** [comment]
> Considering this is WinForms based as well, it is better be done on top of the existing `winforms.py` implementation

I constructed this on top of `winforms.py` by replacing the Trident specific code with what was needed to setup the Edge WebView. However I agree that it would be better to leave all the generic WinForms initializations in one place for easier future maintainability. I will start working on it as soon as I get some more spare time from work.

> with a healthy amount of conditions. I have done it this way in the CEF implementation [here](https://github.com/r0x0r/pywebview/blob/cef/webview/winforms.py). All the Edge initialisation could be done using inside a `_create_edge_browser` function. The best course of action would be probably to rebase your branch on top of the `cef` branch and go there.

If you don't mind me making a suggestion : I checked your CEF implementation code, and IMHO, I think a solution using a base class with all the WinForms initialization code, and subclasses with the specific code for each webview approach would be more fitting. I could also help out with the CEF implementation, if needed.

**Comment by r0x0r** [comment]
Class inheritance sounds good to me, as long as it is not overly complicated just for the sake of it. The CEF implementation is platform agnostic (even though it works only on Windows), so the subclassed version of winforms would be just some form of a glue component between `winforms.py` and `cef.py`. I also would like to keep all the winforms related stuff in `winforms.py` for now.

The Edge should the default renderer for compatible systems Windows 10 >= version 1803 and .NET Framework >= 4.6.2. As long as the requirements are met, it should be selected by default. I think there is no need for a GUI switch.

**Comment by r0x0r** [comment]
There is a major [refactoring](https://github.com/r0x0r/pywebview/issues/272) planned for the version 3.0, which will introduce breaking API changes and will probably result in consolidation of different implementations. So I would not put much effort into getting the current architecture right at this point.

By `winforms stuff` I mean everything WinForms related, incuding Trident, Edge and CEF glue code.

Here is how you programmatically get a .NET version.
https://docs.microsoft.com/en-us/dotnet/api/system.environment.version?redirectedfrom=MSDN&view=netframework-4.7.2#System_Environment_Version

**Comment by r0x0r** [comment]
@HeavenVolkoff 
Here is the CEF implementation https://github.com/r0x0r/pywebview/pull/310

**Comment by HeavenVolkoff** [comment]
Nice work,
As soon as I get some more spare time I will take a look on your changes and see how to better adapt my code to fit everything together.

**Comment by r0x0r** [comment]
@HeavenVolkoff 
API refactoring is more or less complete. I will start looking into incorporating this into the code. I will go with the same route as with CEF, unless you have a better architecture in mind.

**Comment by HeavenVolkoff** [comment]
Hey man,
Sorry for the delay answering. I really want to keep working on this, and I have some neat solutions to implement and merge into the new architecture. However, I am very short on time (due to work and college). So I will only be able to continue this around July. If you want you can merge this as is, but the caveats I mentioned in the first post are still there. Alternatively, we could hold this for a future minor release. Up to you.

**Comment by r0x0r** [comment]
@HeavenVolkoff 
I incorporated your changes in the [edge-support](https://github.com/r0x0r/pywebview/tree/edge-support) branch using the new architecture. 
Anyway let's continue discussion [here](https://github.com/r0x0r/pywebview/issues/243). I am closing this PR.

**Pull request closed without merging**
