### PR TITLE
WIP: Fix for #245 to add minimized functionality

### LINKED ISSUE #245: Need pywebview to start minimized
### Specification
- Platform: MacOS High Sierra
- Version: 2.0.3

### Description
Need pywebview window to start minimized. Cannot find a way to do it.

### PR DESCRIPTION
**Pull request by baldyeagle**
This is currently a work in progress (feedback welcome). Closes #245.

### CODE REVIEW

**Comment by baldyeagle** [comment]
On macOS, I cannot seem to *find* the minimized window after it starts or "deminiaturize"/un-minimize once the application starts. The terminal will still show the thread is active and I have to force close a "Python" window, even after I stop Python in the terminal.

**Comment by r0x0r** [comment]
Thanks for the PR!

Have you tried applicationShouldHandleReopen delegate as described here?
https://stackoverflow.com/questions/18463333/how-to-programmatically-launch-an-osx-app-in-minimized-mode

The delegate method should be implemented inside `class AppDelegate(AppKit.NSObject):`

**Comment by r0x0r** [comment]
Closing due inactivity.

**Comment by baldyeagle** [comment]
Sorry for dropping this work. I did try using the applicationShouldHandleReopen delegate method, but I kept getting exceptions.

**Pull request closed without merging**
