### PR TITLE
[All] Refactor API calls to remove duplicate code

### PR DESCRIPTION
**Pull request by shivaprsdv**
Rewrote the original #207 to use decorators.

### CODE REVIEW

**Comment by r0x0r** [comment]
Good work! One thing, maybe give `api_call` a more descriptive name, like `handle_exceptions` or something along these lines?
Other that, ok to merge.

**Comment by shivaprsdv** [comment]
Hm, isn't `api_call` is more descriptive than `handle_exceptions`? The latter
feels a bit generic and vague; it can mean handle all sorts of exceptions, while
the purpose of the decorator is to handle a very small subset of them, _specific_
to API calls. It reads like: "what follows is an `api_call`"; if someone ask what
an `api_call` is or does, well it is spelled out in its docstring.

But if you insist, it's okay with me, I shall change it.

**Comment by shivaprsdv** [comment]
Another thing, I have modified the commit to prefix `api_call` with an underscore
to mark it as private.

**Comment by r0x0r** [comment]
Let's leave it as _api_call, until a better name manifests itself.

**Pull request merged**
