### PR TITLE
[Cocoa] Add background color 

### PR DESCRIPTION
**Pull request by shivaprsdv**
Also added an example script.

We use another webview as the placeholder till the webview is loaded.
Param background_color and loading_image become the CSS background-color
and background-image of the webview's <body> respectively. This is the
easiest hack that is also portable across platfroms. :)

### CODE REVIEW

**Comment by r0x0r** [comment]
Doesn't using another webview defeat the purpose? The idea is to display a
loading indicator as quickly as possible until the actual webview is
loaded. Having another webview will just introduce another delay.

**Comment by shivaprsdv** [comment]
Uh. Isn't the delay associated with loading an HTTP request? This doesn't
load any request, just load a local image file. I don't see any white screen.

Wait let me check.

**Comment by shivaprsdv** [comment]
Stupid me. You were right. There's a brief white flashing. I didn't notice
before because I was running all the scripts from a fullscreen terminal!

And here I was thinking I had found an ingenious hack. 😕 Let me check
if there is a workaround.

**Comment by shivaprsdv** [comment]
Okay, let us get the better out of it. The delay for displaying the placeholder
webview must be very small even on slower machines (unless the loading_image
is something extreme-super huge, which is unlikely). So the window can be safely
held back till it finishes loading. We switch to the main webview once it finishes
loading (which may typically take longer).

It's not as easy with the native Cocoa API's to display animated GIFs and stuff.
Must be the same with other platforms as well, right? This would be a nice hack
if we could pull it off..

**Comment by shivaprsdv** [comment]
Now this revision doesn't flash the white background.

**Comment by r0x0r** [comment]
I have tested with [Next](http://flowrl.com/next) with both OSX and Windows. With OSX the loading time is barely noticeable (a second or so), while on Windows the white background stays for several seconds.
I would approach this problem by implementing a background color for a webview window in the first place. That should be not be too hard. This way the loading progress could be implemented in a gradual manner: Background color of the application (set by pywebview) -> Loading animation of the application (set inside the application) -> the fully loaded app.

**Comment by shivaprsdv** [comment]
Modified PR according to [issue comment](https://github.com/r0x0r/pywebview/issues/90#issuecomment-301610310).

**Comment by r0x0r** [comment]
The background color is still visible for the title bar after the webview is loaded. Strangely enough the problem does not occur when a breakpoint is set in the webView_didFinishLoadForFrame_ handler. Also the background color disappears when the window is dragged to another monitor. 
screen shot 2017-05-17 at 14 47 07

**Comment by shivaprsdv** [comment]
Fixed.

Also [fixed](https://github.com/r0x0r/pywebview/pull/110/files#diff-2ec81f56c33197a32ca5ae4c092a6a2aR411) hex being converted to wrong color space (`SRGB` instead of `Calibrated`).

**Pull request merged**
