### PR TITLE
Refactor API calls to remove duplicate code

### PR DESCRIPTION
**Pull request by shivaprsdv**
@r0x0r This is a change at the core, hence the PR.

### CODE REVIEW

**Comment by r0x0r** [comment]
This is too implicit in my opinion. How about doing the same thing using decorators? There could be a decorator for exception handling.

**Comment by shivaprsdv** [comment]
Er, what is too implicit? And I don't know much about decorators. 🤔

**Comment by r0x0r** [comment]
Decorators are dead easy, even though the concept might sound scary. In fact `_call_api` can be recycled for a decorator.  
Here is a good intro on decorators https://realpython.com/primer-on-python-decorators/

**Comment by shivaprsdv** [comment]
Okay, I've got two things:

1. I read that article about decorators and got it. Rewrote the refactor to
use them.
2. The last time you pulled from GitHub, seems things didn't go very well.
Stuff like the Readme about `webview.start` came back. So I set out to
straighten out the commit history a bit. Succeeded, but messed up this
PR in the process. I'll open a new one.

I have done a rebase, you'll have fetch and hard checkout (when things
like this happen, I tend to delete the local branch and checkout afresh).
Pulling won't help; I am sorry for this inconvenience, but otherwise you
would have had to repeat a lot of changes you made upstream.

**Pull request merged**
