### PR TITLE
SSL support for internal server

### PR DESCRIPTION
**Pull request by keredson**
I merged w/ your new threaded adapter, but this doesn't use it in SSL mode (yet).

This *only* supports the GTK backend ATM.  (I'm traveling, don't have access to test anything else ATM.)  Will look into the API for the others later.  I intentionally left it so it will fail (as `add_tls_cert()` won't exist) if you try to use it with another backend. 

This is quite a bit bigger than I anticipated.  I'm not familiar w/ bottle's internals, there may be a better way to wrap the socket w/ bottle mixins.

https://github.com/r0x0r/pywebview/issues/1034

### CODE REVIEW

**Comment by keredson** [comment]
https://stackoverflow.com/questions/68347874/webview2-server-certificate-custom-validation claims it's not possible w/ WinForms / Chromium

**Comment by keredson** [comment]
bah.  cefpython doesn't support python 3.10:
image

looks like 3.9 is the max:
https://github.com/cztomczak/cefpython/blob/master/src/common/cefpython_public_api.h

**Comment by keredson** [comment]
@r0x0r summary:

- GTK/QT work
- Cocoa works by allowing all certs (no verification, but still useful IMO)
- Webkit.WinForms didn't find any examples, and one claim it's not possible
- CEF didn't work w/ the default python version in win11
- MSHTML is deprecated, so didn't look into
- so all windows renderers throw `NotImplementedError`
- the test failure is the same as in master (timeout - looks like MSHTML is hanging)
- I didn't touch the client cert side of things yet

I'm way over the time-budget I intended for this, I really only care about/need the GTK version, and my macos/windows knowledge is pretty pathetic, so I'm prob. going to leave this as-is for now.  Your call if you want to merge w/o full renderer coverage (and let someone else who cares about windows add to it) or just keep the PR around for someone else to use as a starting point.

Project's great BTW, thanks!

**Comment by r0x0r** [comment]
Good work @keredson 

I found this example for Winforms. Seems like it is possible to catch certificate error and set to ignore it.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.servercertificateerrordetected?view=webview2-dotnet-1.0.1518.46

**Comment by keredson** [comment]
@r0x0r no answer, just what i found...

breaking it up:
```
            protection_space = challenge.protectionSpace()
            print('protection_space', protection_space)
            authenticationMethod = protection_space.authenticationMethod
            print('authenticationMethod', authenticationMethod())
            server_trust = protection_space.serverTrust
            print('server_trust', server_trust)
            server_trust_called = server_trust()
            print('server_trust_called', server_trust_called)
            credential = AppKit.NSURLCredential.credentialForTrust_(server_trust_called)
```

accessing each of these properties returns a `native-selector` (i assume a pyobjc thing) which has to be called to get the actual value.

the warning is emitted on `server_trust()`.  it is not on `authenticationMethod()` or any other property (tho that's the only non-primitive that's not null).

NSURLProtectionSpace: https://developer.apple.com/documentation/foundation/nsurlprotectionspace

google only finds https://github.com/ronaldoussoren/pyobjc/issues/493 and https://github.com/ronaldoussoren/pyobjc/issues/298

**Comment by r0x0r** [comment]
I found a solution to Cocoa pyobjcpointer warnings.

Windows seems doable, but it requires a) adding a certificate to the global certificate store b) administrator permissions to do so. Both are rather cumbersome, so let's leave Windows out of this for now.

**Pull request merged**
