### PR TITLE
Delete the hack of edgechromium's console and alert

### PR DESCRIPTION
**Pull request by ODtian**
console and alert in edgechromium is well fixed, now you can use devtool.

### CODE REVIEW

**Comment by r0x0r** [comment]
What does alert dialog look like in Edge Chromium? The main reason for this hack is to hide the website address in the alert dialog title bar.

**Comment by ODtian** [comment]
图片
Yes, it seems that website address didnt appear

**Comment by r0x0r** [comment]
What does alert box's title say?

**Comment by ODtian** [comment]
this website prompts

**Pull request merged**
